import type { EconomicEvent } from "../types.js";
const at = (day: number) => `2026-07-${String(day).padStart(2, "0")}T12:00:00Z`;
const source = (verification: EconomicEvent["source"]["verification"], reference: string) => ({
  name: "synthetic_scenario",
  type: "synthetic_demo",
  verification,
  reference,
});
export function autonomousBusinessScenario(): EconomicEvent[] {
  const base = {
    schemaVersion: "1" as const,
    currency: "USDC",
    agentId: "agent_research_1",
    ventureId: "venture_research_briefs",
  };
  return [
    {
      ...base,
      externalId: "capital_001",
      occurredAt: at(1),
      kind: "capital",
      direction: "inflow",
      amount: "100.00",
      category: "owner_capital",
      source: source("self_reported", "synthetic-capital"),
    },
    {
      ...base,
      externalId: "transfer_001",
      occurredAt: at(1),
      kind: "transfer",
      direction: "outflow",
      amount: "40.00",
      category: "internal_wallet_transfer",
      relatedEventId: "transfer_002",
      source: source("system_observed", "synthetic-wallet-transfer"),
    },
    {
      ...base,
      externalId: "transfer_002",
      occurredAt: at(1),
      kind: "transfer",
      direction: "inflow",
      amount: "40.00",
      category: "internal_wallet_transfer",
      relatedEventId: "transfer_001",
      source: source("system_observed", "synthetic-wallet-transfer"),
    },
    {
      ...base,
      externalId: "llm_001",
      occurredAt: at(2),
      kind: "expense",
      direction: "outflow",
      amount: "6.40",
      category: "llm_usage",
      experimentId: "experiment_direct_outreach",
      source: source("receipt_supplied", "synthetic-llm-receipt"),
    },
    {
      ...base,
      externalId: "hosting_001",
      occurredAt: at(2),
      kind: "expense",
      direction: "outflow",
      amount: "4.00",
      category: "hosting_compute",
      source: source("receipt_verified", "synthetic-hosting-receipt"),
    },
    {
      ...base,
      externalId: "domain_001",
      occurredAt: at(3),
      kind: "expense",
      direction: "outflow",
      amount: "12.00",
      category: "domain",
      source: source("receipt_supplied", "synthetic-domain-receipt"),
    },
    {
      ...base,
      externalId: "ad_001",
      occurredAt: at(5),
      kind: "expense",
      direction: "outflow",
      amount: "18.00",
      category: "advertising",
      experimentId: "experiment_paid_advertising",
      source: source("receipt_verified", "synthetic-ad-receipt"),
    },
    {
      ...base,
      externalId: "x402_tool_001",
      occurredAt: at(6),
      kind: "expense",
      direction: "outflow",
      amount: "1.25",
      category: "x402_purchase",
      experimentId: "experiment_direct_outreach",
      source: source("onchain_verified", "synthetic-x402-receipt"),
      transactionHash: "0x1111111111111111111111111111111111111111111111111111111111111111",
    },
    {
      ...base,
      externalId: "revenue_001",
      occurredAt: at(8),
      kind: "revenue",
      direction: "inflow",
      amount: "24.00",
      category: "customer_revenue",
      customerId: "customer_alpha",
      experimentId: "experiment_direct_outreach",
      source: source("receipt_verified", "synthetic-invoice-alpha"),
    },
    {
      ...base,
      externalId: "revenue_002",
      occurredAt: at(10),
      kind: "revenue",
      direction: "inflow",
      amount: "24.00",
      category: "customer_revenue",
      customerId: "customer_beta",
      experimentId: "experiment_direct_outreach",
      source: source("onchain_verified", "synthetic-invoice-beta"),
    },
    {
      ...base,
      externalId: "revenue_003",
      occurredAt: at(12),
      kind: "revenue",
      direction: "inflow",
      amount: "10.00",
      category: "customer_revenue",
      customerId: "customer_gamma",
      experimentId: "experiment_paid_advertising",
      source: source("self_reported", "synthetic-invoice-gamma"),
    },
    {
      ...base,
      externalId: "refund_001",
      occurredAt: at(14),
      kind: "refund",
      direction: "outflow",
      amount: "4.00",
      category: "customer_refund",
      customerId: "customer_alpha",
      experimentId: "experiment_direct_outreach",
      relatedEventId: "revenue_001",
      source: source("receipt_verified", "synthetic-refund-alpha"),
    },
    {
      ...base,
      externalId: "fee_001",
      occurredAt: at(15),
      kind: "fee",
      direction: "outflow",
      amount: "0.35",
      category: "blockchain_transaction_fee",
      source: source("onchain_verified", "synthetic-chain-fee"),
    },
    {
      ...base,
      externalId: "ad_llm_001",
      occurredAt: at(16),
      kind: "expense",
      direction: "outflow",
      amount: "3.60",
      category: "llm_usage",
      experimentId: "experiment_paid_advertising",
      source: source("receipt_supplied", "synthetic-ad-copy-llm"),
    },
    {
      ...base,
      externalId: "withdrawal_001",
      occurredAt: at(20),
      kind: "withdrawal",
      direction: "outflow",
      amount: "8.00",
      category: "owner_withdrawal",
      source: source("system_observed", "synthetic-owner-withdrawal"),
    },
  ];
}
